
# kind
MEDIAN__MAD = 0
MEDIAN__PART_SPLIT_MAD = 6
MEDIAN__FULL_SPLIT_MAD = 8
MEDIAN__IQR = 97
MEDIAN__SPLIT_IQR = 98
ROB_MEAN__ROB_VAR = 1
ROB_MEAN__MAD = 2
ROB_MEAN__PART_SPLIT_MAD = 7
MEAN__STD = 99
